#!/bin/sh

# Set Session Name
SESSION="Dev"
SESSIONEXISTS=$(tmux list-sessions | grep $SESSION)

# Only create tmux session if it doesn't already exist
if [ "$SESSIONEXISTS" = "" ]
then
    # Start New Session with our name
    tmux new-session -d -s $SESSION

    # Name first Pane and start zsh
    tmux rename-window -t 1 'Main'
    tmux send-keys -t 'Main' 'zsh' C-m 'clear' C-m # Switch to bind script?

    # Create and setup pane for hugo server
    tmux new-window -t $SESSION:2 -n 'PSUS'
    tmux send-keys -t 'PSUS' 'psus' C-m # Switch to bind script?

    # setup Writing window
    tmux new-window -t $SESSION:3 -n 'VIM'
    tmux send-keys -t 'VIM' "nvim" C-m

    # Setup an additional shell
    tmux new-window -t $SESSION:4 -n 'NGROK'
    tmux send-keys -t 'NGROK' "zsh" C-m 'clear' C-m
fi

# Attach Session, on the Main window
tmux attach-session -t $SESSION:1
