-- Per-workspace Odoo setups, shared by configs/dap-py.lua and chadrc.lua.
-- First `match` wins so keep the fallback last; matches are Lua patterns (`%-`).

local M = {}

M.setups = {
  {
    key = "odoofin",
    match = "/Dev/src/odoofin%-env",
    root = function() return "/home/andg/Dev/src/odoofin-env" end,
    prompt_label = "OdooFin",
    program = "/home/andg/Dev/src/odoofin-env/odoo/odoo-bin",
    odoorc = function(root) return root .. "/.oenv.conf" end,
    odools_profile = "odoofin",
    tag = "IN ODOOFIN",
    tag_hl = "%#St_lspWarning#",
    tag_icon = "\u{f057}",
  },
  {
    key = "iap",
    match = "/Dev/src/iap",
    root = function() return "/home/andg/Dev/src/iap" end,
    prompt_label = "IAP",
    program = "/home/andg/Dev/src/iap/odoo-18.0/odoo-bin",
    odoorc = function(root) return root .. "/.oenv.conf" end,
    odools_profile = "iap",
    tag = "IN IAP",
    tag_hl = "%#St_lspError#",
    tag_icon = "\u{f057}",
  },
  -- Worktree envs from `owt` (see ~/.bash_aliases_odoo). One entry covers all of
  -- them: the slug is only known at runtime, so the paths are functions of the
  -- env root. `.oenv.conf` is generated by the same code the shell uses.
  {
    key = "worktree",
    match = "/Dev/wt/[^/]+",
    root = function(cwd) return cwd:match("^(.*/Dev/wt/[^/]+)") end,
    prompt_label = function(root) return vim.fs.basename(root) end,
    program = function(root) return root .. "/odoo/odoo-bin" end,
    odoorc = function(root) return root .. "/.oenv.conf" end,
    tag = function(root) return "IN " .. vim.fs.basename(root):upper() end,
    odools_profile = "Custom Setup",
    tag_hl = "%#St_lspWarning#",
    tag_icon = "\u{f057}",
  },
  {
    key = "odoo",
    program = "/home/andg/Dev/src/odoo/odoo-bin",
    odools_profile = "Custom Setup",
  },
}

--- The setup owning `cwd` (defaults to the current working directory).
--- Entries with a `root` resolve their function fields against it; static
--- entries are returned untouched.
function M.current(cwd)
  cwd = cwd or vim.fn.getcwd()
  for _, setup in ipairs(M.setups) do
    if not setup.match or cwd:match(setup.match) then
      local root = setup.root and setup.root(cwd)
      if not root then
        return setup
      end
      local resolved = vim.tbl_extend("force", {}, setup)
      resolved.root = root
      for _, key in ipairs({ "program", "odoorc", "prompt_label", "tag" }) do
        if type(resolved[key]) == "function" then
          resolved[key] = resolved[key](root)
        end
      end
      return resolved
    end
  end
end

return M
